### PR TITLE
Added Tim Sort Algorithm

### PR DESCRIPTION
**Pull request by Karan-05**

### CODE REVIEW

**Comment by balbhimk** [comment]
@Karan-05 hello you want to just change your file name as mentioned in issue description so do changes to make valid PR

**Comment by Karan-05** [comment]
Done

**Comment by balbhimk** [comment]
done merged!
thanks for contributing.....
give a star...

**Comment by Karan-05** [comment]
Ok Thanks
and Done this side too

**Comment by Karan-05** [comment]
Hi can you please add the hacktoberfest-accepted label

**Comment by Karan-05** [comment]
Thank you

**Pull request merged**
